### ISSUE TITLE
Missing item - Elder Selassy'e

### ISSUE THREAD

**Issue by Stever1388** [jansepke/anno-toolkit#15]
I noticed an item is missing from the database - the Town Hall item "Elder Selassy'e" which is for Enbesan residences, and reduces Dried Meat consumption by 20% and increases happiness +7. I got it from a quest but it's also available from Emperor Ketema.

As a side note, I've noticed that a lot of the items that have durations and then expire (like the ones that provide residents needs for 5 minutes) aren't in the database either, I'm not sure if that's deliberate or not.

**Comment by jansepke** [comment]
Thanks for reporting, there was a bug in the processing of the game data files. Now the "Elder Selassy'e" item and 5 other are visible.

Items that have a duration and then expire are currently not supported in the effect list. These items are only visible in the expedition views. Do have a use case for having them also in the effect list? (beside being more complete). As the lists are already quite long and take some time to load we want to improve loading performance first before adding this feature.

**Comment by Stever1388** [comment]
I don't really have a use case for having those other items in the list other than just completeness. I hardly use those items anyway and I agree that performance is more important than having those items in there.
