### ISSUE TITLE
Some English content is in German

### ISSUE THREAD

**Issue by Stever1388** [jansepke/anno-toolkit#4]
It started happening recently, but sometimes the content is in German instead of English. Seems to happen with the Extra Good and Replaced Input fields for Trade Unions.

For example, searching for _Gramophone Factory_ and then _Extra Goods_ shows results _Science Whizz_ which says _Extra Goods: 1/5 Glühfäden_

**Comment by jansepke** [comment]
We did some work on the translations but I'm not able to reproduce your issue. I searched directly for Science Whizz or only filtered by Gramophone Factory and then Extra Goods. Can you still reproduce this issue?

**Comment by Stever1388** [comment]
It seems to be working now for me as well. Maybe the work on the translations fixed it somehow.

**Comment by jansepke** [comment]
The problem just happened again during development, and I fixed it permanently. Thanks for reporting.
